#Create a replication controller for creating 3 replicas of httpd

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    author: sohail
spec:
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels:
        author: sohail
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...