#Create a pod defintion file to start a mysql pod and pass the environment
#varible using the above secret.

apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    author: sohail
    type: db
spec:
  containers:
    - name: mydb
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
...